### ISSUE TITLE
unable to finish transform, error:  Failed to parse declaration "boxShadow: 1px 1px 5px 2px rgba(188,183,183,0.15)"

### ISSUE THREAD

**Issue by thejerrytan** [peconia/css-to-react-native-stylesheet#3]
trying to parse my css file and got the above error.

Here is the section of my css file:

.Schedule_Export_Img {
  padding: 40px;
  cursor: pointer;
  background-color: #FFFFFF;
  box-shadow: 1px 1px 5px 2px rgba(188,183,183,0.15);
  opacity: 0.5;
}

.Schedule_Export_Img_Selected {
  opacity: 1;
  box-shadow: 1px 1px 5px 2px rgba(188,183,183,0.5);
  border: 1px solid #F1EFEF;
}

**Comment by peconia** [comment]
Please check the documentation for [css-to-react-native-transform](https://www.npmjs.com/package/css-to-react-native-transform) and [css-to-react-native](https://github.com/styled-components/css-to-react-native). You can open an issue there if needed, this tool is just wrapping up those and doesn't hold the logic for the parsing.
